/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import ui.Admin.AdminWorkAreaJPanel;
import model.System;
import ui.Dashboard.DashboardWorkAreaJPanel;
import ui.Patient.PatientWorkAreaJPanel;

/**
 *
 * @author Ketki Kule <kule.k@northeastern.edu>
 */
public class MainJFrame extends javax.swing.JFrame {

    System system;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        system = new System();
        UtilityClass utilityClass = new UtilityClass(system);
        JLabel picLabel = new JLabel(new ImageIcon(getClass().getResource("/res/bp_1_resized_1.jpg")));
        picLabel.setPreferredSize(new Dimension(50, 50));
        displayPanel.add(picLabel);
        jSplitPane1.setDividerLocation(300);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnAdminPanel = new javax.swing.JButton();
        btnPatientPanel = new javax.swing.JButton();
        btnDashboardPanel = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(234, 226, 214));
        controlPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 195, 170), 2, true));
        controlPanel.setForeground(new java.awt.Color(213, 195, 170));

        btnAdminPanel.setBackground(new java.awt.Color(134, 118, 102));
        btnAdminPanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAdminPanel.setForeground(new java.awt.Color(234, 226, 214));
        btnAdminPanel.setText("Admin");
        btnAdminPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdminPanel.setContentAreaFilled(false);
        btnAdminPanel.setOpaque(true);
        btnAdminPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminPanelActionPerformed(evt);
            }
        });

        btnPatientPanel.setBackground(new java.awt.Color(134, 118, 102));
        btnPatientPanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPatientPanel.setForeground(new java.awt.Color(234, 226, 214));
        btnPatientPanel.setText("Patient");
        btnPatientPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPatientPanel.setContentAreaFilled(false);
        btnPatientPanel.setOpaque(true);
        btnPatientPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientPanelActionPerformed(evt);
            }
        });

        btnDashboardPanel.setBackground(new java.awt.Color(134, 118, 102));
        btnDashboardPanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDashboardPanel.setForeground(new java.awt.Color(234, 226, 214));
        btnDashboardPanel.setText("Dashboard");
        btnDashboardPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDashboardPanel.setContentAreaFilled(false);
        btnDashboardPanel.setOpaque(true);
        btnDashboardPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(btnPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(btnAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addComponent(btnDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnPatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(controlPanel);

        displayPanel.setBackground(new java.awt.Color(234, 226, 214));
        displayPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 195, 170), 2, true));
        displayPanel.setForeground(new java.awt.Color(213, 195, 170));
        displayPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(displayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminPanelActionPerformed
        // TODO add your handling code here:
        AdminWorkAreaJPanel adminWorkAreaJPanel = new AdminWorkAreaJPanel(displayPanel, system);
        displayPanel.add(adminWorkAreaJPanel);
        CardLayout cardLayout = (CardLayout) displayPanel.getLayout();
        cardLayout.next(displayPanel);
    }//GEN-LAST:event_btnAdminPanelActionPerformed

    private void btnPatientPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientPanelActionPerformed
        // TODO add your handling code here:
        if (system.getPersonDirectory().getPersonsList().size() >= 1) {
            PatientWorkAreaJPanel patientWorkArea = new PatientWorkAreaJPanel(displayPanel, system);
            displayPanel.add(patientWorkArea);
            CardLayout cardLayout = (CardLayout) displayPanel.getLayout();
            cardLayout.next(displayPanel);
        } else {
            JOptionPane.showMessageDialog(null, "No Person Details Added ", "Please Fill Person Details First", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_btnPatientPanelActionPerformed

    private void btnDashboardPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardPanelActionPerformed
        // TODO add your handling code here:
        if (system.getPersonDirectory().getPersonsList().size() >= 1) {
            DashboardWorkAreaJPanel dashboardWorkArea = new DashboardWorkAreaJPanel(displayPanel, system);
            displayPanel.add(dashboardWorkArea);
            CardLayout cardLayout = (CardLayout) displayPanel.getLayout();
            cardLayout.next(displayPanel);
        } else {
            JOptionPane.showMessageDialog(null, "No Person Details Added ", "Please Fill Person Details First", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnDashboardPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminPanel;
    private javax.swing.JButton btnDashboardPanel;
    private javax.swing.JButton btnPatientPanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
