/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Restaurant.Menu;
import Business.Restaurant.MenuItem;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ketki Kule <kule.k@northeastern.edu>
 */
public class AddEditMenuItemJPanel extends javax.swing.JPanel {

    private Menu menu;
    private MenuItem menuItem;
    private JPanel displayPanel;
    private int operationId;

    /**
     * Creates new form AddEditMenuItemJPanel
     */
    public AddEditMenuItemJPanel(JPanel displayPanel, Menu menu, MenuItem menuItem, int operationId) {
        initComponents();
        this.displayPanel = displayPanel;
        this.menu = menu;
        this.menuItem = menuItem;
        this.operationId = operationId;
        loadData();
    }

    private void loadData() {
        if (operationId == 1) {
            txtMenuItem.setText(menuItem.getItemName());
            txtIngrediants.setText(menuItem.getIngredients());
            txtAdditionalNote.setText(menuItem.getIngredients());
            txtServingSize.setText(String.valueOf(menuItem.getServes()));
            txtPrice.setText(String.valueOf(menuItem.getPrice()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMenuItem = new javax.swing.JLabel();
        txtMenuItem = new javax.swing.JTextField();
        lblIngrediant = new javax.swing.JLabel();
        txtIngrediants = new javax.swing.JTextField();
        lblservingSize = new javax.swing.JLabel();
        txtServingSize = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblAdditionalNote = new javax.swing.JLabel();
        txtAdditionalNote = new javax.swing.JTextField();

        setBackground(new java.awt.Color(234, 226, 214));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Menu Item");

        lblMenuItem.setText("Menu Item Name :");

        lblIngrediant.setText("Item Ingredients :");

        txtIngrediants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngrediantsActionPerformed(evt);
            }
        });

        lblservingSize.setText("Serves (No Of People) :");

        lblPrice.setText("Price :");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAdditionalNote.setText("Additional Note :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(234, 234, 234))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIngrediant)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblMenuItem)
                                            .addGap(74, 74, 74))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblservingSize, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAdditionalNote, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPrice)
                                        .addComponent(txtAdditionalNote)
                                        .addComponent(txtMenuItem)
                                        .addComponent(txtIngrediants)
                                        .addComponent(txtServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(455, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngrediant, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngrediants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblservingSize)
                    .addComponent(txtServingSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdditionalNote)
                    .addComponent(txtAdditionalNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(506, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMenuItem.getText().isEmpty() || txtIngrediants.getText().isEmpty() || txtPrice.getText().isEmpty() || txtServingSize.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please Fill All Fields ", "Empty Fields", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String itemName = txtMenuItem.getText();
            String ingrediant = txtIngrediants.getText();
            int servingSize = Integer.parseInt(txtServingSize.getText());
            String additionalNote = txtAdditionalNote.getText();
            double price;
            try {
                price = Double.parseDouble(txtPrice.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please Enter Valid Price Value ", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (operationId == 0) {
                menu.getMenuList().add(new MenuItem(itemName, ingrediant, servingSize, price, additionalNote));
                JOptionPane.showMessageDialog(null, "Menu Item Added", "Entry Added", JOptionPane.INFORMATION_MESSAGE);
            } else {
                menuItem.setItemName(itemName);
                menuItem.setIngredients(ingrediant);
                menuItem.setAdditionalNote(additionalNote);
                menuItem.setPrice(price);
                menuItem.setServes(servingSize);
                JOptionPane.showMessageDialog(null, "Menu Item Updated", "Entry Updated", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Values ", "Invalid Value", JOptionPane.WARNING_MESSAGE);
                return;
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        displayPanel.remove(this);
        Component[] componentArray = displayPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageMenuJPanel workArea = (ManageMenuJPanel) component;
        workArea.loadMenuTable();
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtIngrediantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngrediantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngrediantsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAdditionalNote;
    private javax.swing.JLabel lblIngrediant;
    private javax.swing.JLabel lblMenuItem;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblservingSize;
    private javax.swing.JTextField txtAdditionalNote;
    private javax.swing.JTextField txtIngrediants;
    private javax.swing.JTextField txtMenuItem;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtServingSize;
    // End of variables declaration//GEN-END:variables
}
