/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Menu;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ketki Kule <kule.k@northeastern.edu>
 */
public class RestaurantInfoJPanel extends javax.swing.JPanel {

    private JPanel displayPanel;
    private UserAccount adminAccount;
    private Restaurant restaurant;

    /**
     * Creates new form RestaurantInfoJPanel
     */
    public RestaurantInfoJPanel(JPanel userProcessContainer, UserAccount account, Restaurant restaurant) {
        initComponents();
        this.displayPanel = userProcessContainer;
        this.adminAccount = account;
        this.restaurant = restaurant;
        loadData();
    }

    private void loadData() {
        txtRestaurantName.setText(restaurant.getRestaurantName());
        txtEmailAdd.setText(restaurant.getEmailAddress());
        txtLicenseNumber.setText(restaurant.getLicenseNumber());
        txtManagerName.setText(restaurant.getManagerName());
        txtTelPh.setText(String.valueOf(restaurant.getTelPhoneNo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRestaurantName = new javax.swing.JLabel();
        lblManagerName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        txtRestaurantName = new javax.swing.JTextField();
        lblLicenseNumber = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblEmailAdd = new javax.swing.JLabel();
        txtEmailAdd = new javax.swing.JTextField();
        lblTelPh = new javax.swing.JLabel();
        txtTelPh = new javax.swing.JTextField();

        lblRestaurantName.setText("Restaurant Name :");

        lblManagerName.setText("Manager Name :");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Restaurant Information");

        txtManagerName.setEditable(false);

        txtLicenseNumber.setEditable(false);

        txtRestaurantName.setEditable(false);

        lblLicenseNumber.setText("License Number :");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblEmailAdd.setText("Email Address :");

        txtEmailAdd.setEditable(false);

        lblTelPh.setText("Telephone Number :");

        txtTelPh.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRestaurantName)
                            .addComponent(lblLicenseNumber)
                            .addComponent(lblManagerName)
                            .addComponent(lblEmailAdd)
                            .addComponent(lblTelPh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTelPh)
                            .addComponent(txtRestaurantName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtManagerName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRestaurantName))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblManagerName)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLicenseNumber)
                    .addComponent(lblLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelPh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelPh))
                .addContainerGap(480, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        displayPanel.remove(this);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblEmailAdd;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblTelPh;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtTelPh;
    // End of variables declaration//GEN-END:variables
}
