/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Admin;

import java.awt.CardLayout;
import java.awt.Component;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Car;
import model.Driver;
import model.Uber;

/**
 *
 * @author Ketki Kule <kule.k@northeastern.edu>
 */
public class AddEditDriveJPanel extends javax.swing.JPanel {

    JPanel displayPanel;
    Uber uber;
    int addEdit;
    String selectedCarSerialNumber = "";

    /**
     * Creates new form AddDriveJPanel
     */
    public AddEditDriveJPanel(JPanel displayPanel, Uber uber, String selectedRow, int addEdit) {
        initComponents();
        this.displayPanel = displayPanel;
        this.uber = uber;
        this.addEdit = addEdit;
        if (addEdit == 1) {
            this.selectedCarSerialNumber = selectedRow;
            btnAdd.setText("Update");
            loadDetails();
        }
    }

    private void loadDetails() {
        for (Driver driver : uber.getDriverDirectory().getDriverList()) {
            if (driver.getSerialNumber().equalsIgnoreCase(selectedCarSerialNumber)) {
                Car car = driver.getCar();
                txtSerialNumber.setText(car.getSerialNumber());
                txtModelNumber.setText(car.getModelNumber());
                txtManufacturer.setText(car.getManufacturer());
                txtCity.setText(driver.getCity());
                yearPickerManufacturingYear.setYear(car.getManufacturingYear());
                txtSeats.setText(car.getSeats() + "");
                Calendar calendar = Calendar.getInstance();
                calendar.clear();
                //assuming start of day
                calendar.set(car.getMaintenanceCertExpiry().getYear(), car.getMaintenanceCertExpiry().getMonthValue() - 1, car.getMaintenanceCertExpiry().getDayOfMonth());
                datePickerMaintenance.setCalendar(calendar);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        newJPanel = new javax.swing.JPanel();
        lblSerialNumber = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        lblManufacturerYear = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        lblModelNumber = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        lblMaintenance = new javax.swing.JLabel();
        datePickerMaintenance = new com.toedter.calendar.JDateChooser();
        yearPickerManufacturingYear = new com.toedter.calendar.JYearChooser();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtSeats = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1169, 779));

        lblSerialNumber.setText("Car Serial Number ");

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("New Driver");

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        lblCity.setText("City");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblManufacturer.setText("Manufacturer");

        lblManufacturerYear.setText("Manufacturing Year");

        txtManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerActionPerformed(evt);
            }
        });

        lblModelNumber.setText("Model Number");

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        lblMaintenance.setText("Car Maintenance Certificate Expiry");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsActionPerformed(evt);
            }
        });

        lblSeats.setText("Seats");

        javax.swing.GroupLayout newJPanelLayout = new javax.swing.GroupLayout(newJPanel);
        newJPanel.setLayout(newJPanelLayout);
        newJPanelLayout.setHorizontalGroup(
            newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanelLayout.createSequentialGroup()
                .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newJPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(318, 318, 318)
                        .addComponent(lblTitle))
                    .addGroup(newJPanelLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSerialNumber)
                            .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(newJPanelLayout.createSequentialGroup()
                                    .addComponent(lblCity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(newJPanelLayout.createSequentialGroup()
                                    .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblModelNumber)
                                        .addComponent(lblMaintenance)
                                        .addComponent(lblSeats))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                        .addComponent(datePickerMaintenance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                                .addGroup(newJPanelLayout.createSequentialGroup()
                                    .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblManufacturer)
                                        .addComponent(lblManufacturerYear))
                                    .addGap(376, 376, 376)
                                    .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                            .addComponent(yearPickerManufacturingYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(newJPanelLayout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(474, Short.MAX_VALUE))
        );
        newJPanelLayout.setVerticalGroup(
            newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newJPanelLayout.createSequentialGroup()
                        .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSerialNumber)
                            .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManufacturer))
                        .addGap(18, 18, 18)
                        .addComponent(lblManufacturerYear)
                        .addGap(6, 6, 6))
                    .addComponent(yearPickerManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelNumber))
                .addGap(18, 18, 18)
                .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaintenance)
                    .addComponent(datePickerMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );

        scrollPanel.setViewportView(newJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            if (txtSerialNumber.getText().length() > 0 && txtCity.getText().length() > 0 && txtModelNumber.getText().length() > 0 && txtManufacturer.getText().length() > 0
                    && txtSeats.getText().length() > 0) {
                boolean isSuccessful = false;
               
                String serialNumber = txtSerialNumber.getText();
                String city = txtCity.getText();
                String modelNumber = txtModelNumber.getText();
                String manufacturer = txtManufacturer.getText();
                int manufacuturingYear = yearPickerManufacturingYear.getYear();
                int seats = Integer.parseInt(txtSeats.getText());
                LocalDate certExpiry = Instant.ofEpochMilli(datePickerMaintenance.getDate().getTime()).atZone(ZoneId.systemDefault()).toLocalDate();

                Car car = new Car(serialNumber, modelNumber, manufacturer, manufacuturingYear, seats, certExpiry);
                Driver driver = new Driver(car, city, true, serialNumber);

                if (addEdit == 0) {
                    boolean isDuplicateEntry = false;
                    for (Driver d : uber.getDriverDirectory().getDriverList()) {
                        if (d.getSerialNumber().equalsIgnoreCase(serialNumber)) {
                            isDuplicateEntry = true;
                            break;
                        }
                    }
                    if (!isDuplicateEntry) {
                        uber.getCarDirectory().addCar(car);
                        uber.getDriverDirectory().addDriver(driver);
                        isSuccessful = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Car Serial Number " + serialNumber + " already exists ", "Successful", JOptionPane.PLAIN_MESSAGE);
                    }

                } else {
                    for (Driver d : uber.getDriverDirectory().getDriverList()) {
                        if (d.getSerialNumber().equalsIgnoreCase(selectedCarSerialNumber)) {
                            d.setCar(car);
                            d.setCity(city);
                            d.setSerialNumber(serialNumber);
                        }
                    }
                    isSuccessful = true;
                }
                if (isSuccessful) {
                    String status = "updated";
                    if(addEdit == 0) {
                        status = "added";
                    }
                    JOptionPane.showMessageDialog(null, "Car details successfully " + status , "Duplicate Entry", JOptionPane.PLAIN_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please All Fields ", "Empty Fields", JOptionPane.WARNING_MESSAGE);

            }

        } catch (Exception ex) {
            System.out.println("Exception " + ex);
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsActionPerformed

    private void backAction() {
        displayPanel.remove(this);
        Component[] componentArray = displayPanel.getComponents();
        Component c = componentArray[componentArray.length - 1];
        ManageDriverJPanel ms = (ManageDriverJPanel) c;
        ms.refreshTable();
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private com.toedter.calendar.JDateChooser datePickerMaintenance;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintenance;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblManufacturerYear;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel newJPanel;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    private com.toedter.calendar.JYearChooser yearPickerManufacturingYear;
    // End of variables declaration//GEN-END:variables
}
