/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Restaurant;

import Business.Customer.Customer;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.Menu;
import Business.Restaurant.MenuItem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Order;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.RestaurantAdminRole.ManageOrderJPanel;

/**
 *
 * @author Ketki Kule <kule.k@northeastern.edu>
 */
public class OrderDetailsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    Menu menu;
    Order order;
    UserAccount userAccount;
    MenuItem menuItem;

    /**
     * Creates new form OrderDetailsJPanel
     */
    public OrderDetailsJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, Restaurant restaurant, Order order, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.menu = restaurant.getMenu();
        this.order = order;
        this.userAccount = userAccount;
        loadData();
    }

    private void loadData() {

        txtStatus.setText(order.getStatus());
        txtCustName.setText(order.getCustomer().getFullName());
        txtCustomerAddress.setText(order.getCustomer().getAddress());
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy hh:mm");
        txtOrderTime.setText(formatter.format(order.getRequestDate()));
        txtCustMsg.setText(order.getMessage());
        txtCustFeedback.setText(order.getCustomerFeedback());

        for (DeliveryMan deliveryMan : ecoSystem.getDeliveryManDirectory().getDeliveryManList()) {
            if (deliveryMan.isAvailable()) {
                comboDeliveryMan.addItem(deliveryMan.getName());
            }
        }

        if (order.getStatus().equals("Delivered")) {
            btnAccept.setEnabled(false);
            btnCancel.setEnabled(false);
        }
        populateTable();

    }

    public void populateTable() {
        double totalprice = 0.0;
        DefaultTableModel model = (DefaultTableModel) tblOrderMenu.getModel();
        model.setRowCount(0);

        for (MenuItem menuItem : order.getMenuItems()) {
            Object[] row = new Object[3];
            row[0] = menuItem;
            row[1] = menuItem.getQuantity();
            row[2] = menuItem.getPrice() * menuItem.getQuantity();
            totalprice += menuItem.getPrice() * menuItem.getQuantity();
            model.addRow(row);
        }

        Object[] row = new Object[2];
        row[0] = "Total";
        row[1] = String.valueOf(totalprice);
        model.addRow(row);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        txtCustName = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JLabel();
        lblCustomerAddress = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        txtOrderTime = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtCustMsg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderMenu = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblDeliveryMan = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        lblCustFeedback = new javax.swing.JLabel();
        txtCustFeedback = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        comboDeliveryMan = new javax.swing.JComboBox<>();

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Order Details");

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCustomerName.setText("Customer Name :");

        txtCustName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCustName.setText("<Value>");

        txtCustomerAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCustomerAddress.setText("<Value>");

        lblCustomerAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCustomerAddress.setText("Customer Address (Drop Off ) :");

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTime.setText("Time :");

        txtOrderTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOrderTime.setText("<Value>");

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMessage.setText("Customer Message :");

        txtCustMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblOrderMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Name", "Item Quantity", "Item Price"
            }
        ));
        jScrollPane2.setViewportView(tblOrderMenu);

        btnAccept.setText("Accept Order");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel Order");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblDeliveryMan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDeliveryMan.setText("Delivery Man Name :");

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStatus.setText("<Value>");

        lblCustFeedback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCustFeedback.setText("Customer Feedback :");

        txtCustFeedback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStatus.setText("Status :");

        comboDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeliveryManActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCustomerAddress)
                                    .addComponent(lblCustFeedback)
                                    .addComponent(lblTime)
                                    .addComponent(lblMessage)
                                    .addComponent(lblDeliveryMan)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(406, 406, 406)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblStatus)
                                    .addComponent(lblCustomerName))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtCustFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOrderTime, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDeliveryMan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(btnAccept)
                        .addGap(175, 175, 175)
                        .addComponent(btnCancel)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatus)
                    .addComponent(lblStatus))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustFeedback)
                    .addComponent(txtCustFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrderTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryMan)
                    .addComponent(comboDeliveryMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        if (order.getStatus().equals("Preparing")) {
            JOptionPane.showMessageDialog(null, "Order Already Accepted", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            order.setStatus("Preparing");
            txtStatus.setText("Preparing");
            for (DeliveryMan deliveryMan : ecoSystem.getDeliveryManDirectory().getDeliveryManList()) {
                if (deliveryMan.getName().equals(comboDeliveryMan.getSelectedItem())) {
                    order.setDeliveryMan(deliveryMan);
                    for (UserAccount user : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
                        if (user.getEmployee().getId() == deliveryMan.getEmployeeId()) {
                            user.getWorkQueue().getWorkRequestList().add(order);
                        }
                    }
                    break;
                }
            }

            JOptionPane.showMessageDialog(null, "Order Accepted Successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageOrderJPanel workArea = (ManageOrderJPanel) component;
        workArea.loadData();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if (order.getStatus().equals("Cancelled")) {
            JOptionPane.showMessageDialog(null, "Order Already Cancelled", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            order.setStatus("Cancelled");
            txtStatus.setText("Cancelled");
            JOptionPane.showMessageDialog(null, "Order Cancelled Successfully", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnCancelActionPerformed

    private void comboDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeliveryManActionPerformed

    }//GEN-LAST:event_comboDeliveryManActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> comboDeliveryMan;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustFeedback;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDeliveryMan;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrderMenu;
    private javax.swing.JLabel txtCustFeedback;
    private javax.swing.JLabel txtCustMsg;
    private javax.swing.JLabel txtCustName;
    private javax.swing.JLabel txtCustomerAddress;
    private javax.swing.JLabel txtOrderTime;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
